import {all,statement,saveArticle,chinaDayStart} from './storage.js';
import {crawlSource,safeUrl} from './crawler.js';
export async function syncSource(db,id,{limit=24,crawl=crawlSource}={}){
 const source=await statement(db,'SELECT * FROM sources WHERE id=?',[id]).first();if(!source)throw new Error('来源不存在');if(!source.enabled)throw new Error('来源已暂停');
 const now=new Date().toISOString(),cutoff=new Date(Date.now()-10*60000).toISOString();
 const lock=await statement(db,"UPDATE sources SET status='running',last_attempt=?,error=NULL WHERE id=? AND (status<>'running' OR last_attempt<?)",[now,id,cutoff]).run();if(!lock.meta.changes)throw new Error('该来源正在同步，请稍后查看运行记录');
 const runId=crypto.randomUUID();await statement(db,"INSERT INTO runs(id,source_id,started_at,status) VALUES (?,?,?,'running')",[runId,id,now]).run();let added=0,updated=0,result;
 try{const known=new Map((await all(db,'SELECT url,content_hash FROM articles WHERE source_id=?',[id])).map(a=>[a.url,a.content_hash]));result=await crawl(source,{limit,known});for(const a of result.articles){const change=await saveArticle(db,a);added+=Number(change==='added');updated+=Number(change==='updated')}
 const status=result.errors.length?(result.articles.length?'partial':'error'):'success';const finished=new Date().toISOString();const detail=JSON.stringify({pages:result.pages,discovered:result.discovered,remaining:result.remaining,entries:result.entries,limit});
 await db.batch([statement(db,'UPDATE sources SET status=?,last_success=CASE WHEN ? THEN ? ELSE last_success END,error=?,detail=? WHERE id=?',[status,result.articles.length?1:0,finished,result.errors.join('\n').slice(0,12000)||null,detail,id]),statement(db,'UPDATE runs SET finished_at=?,status=?,added=?,updated=?,errors=?,pages=? WHERE id=?',[finished,status,added,updated,result.errors.join('\n').slice(0,12000),result.pages,runId])]);return{runId,status,added,updated,...result,articles:undefined};
 }catch(e){const error=String(e.message||e);await db.batch([statement(db,"UPDATE sources SET status='error',error=? WHERE id=?",[error,id]),statement(db,"UPDATE runs SET status='error',finished_at=?,errors=? WHERE id=?",[new Date().toISOString(),error,runId])]);throw e}
}
export async function api(request,env){const db=env.DB,u=new URL(request.url),path=u.pathname;
 if(request.method!=='GET'){const origin=request.headers.get('origin');if(origin&&origin!==u.origin)return Response.json({error:'来源验证失败'},{status:403});if(!request.headers.get('content-type')?.startsWith('application/json'))return Response.json({error:'需要 JSON 请求'},{status:415})}
 if(path==='/api/state'){
 const sources=await all(db,'SELECT s.*,(SELECT count(*) FROM articles a WHERE a.source_id=s.id) AS article_count FROM sources s ORDER BY s.created_at,s.id');
 const stats=await statement(db,'SELECT count(*) total,sum(CASE WHEN collected_at>=? THEN 1 ELSE 0 END) new_count,max(checked_at) last_check FROM articles',[chinaDayStart()]).first();
 const categories=await all(db,'SELECT category,count(*) count FROM articles GROUP BY category');
 const runs=await all(db,'SELECT r.*,s.name source_name FROM runs r LEFT JOIN sources s ON s.id=r.source_id ORDER BY started_at DESC LIMIT 50');
 const digests=await all(db,'SELECT * FROM digests ORDER BY created_at DESC LIMIT 1');
 return Response.json({sources,stats,categories,runs,digest:digests[0]||null,runtime:env.RUNTIME||'cloud',schedule:{time:'每天 07:00',timezone:'Asia/Shanghai',mode:env.SCHEDULE_MODE||'pending'}});
 }
 if(path==='/api/company/reset'&&request.method==='POST'){const x=await request.json();if(x.confirm!=='清空当前公司')throw new Error('请输入“清空当前公司”确认');const n=new Date().toISOString();await db.batch([statement(db,"DELETE FROM policy_tasks WHERE company_id='current'"),statement(db,"UPDATE company SET name='新公司',industry='',region='',scale='',qualifications='',needs='',updated_at=? WHERE id='current'",[n])]);return Response.json({reset:true})}
 if(path==='/api/company'&&request.method==='PUT'){const x=await request.json();if(!String(x.name||'').trim())throw new Error('公司名称不能为空');const fields=['name','industry','region','scale','qualifications','needs'];await statement(db,"UPDATE company SET name=?,industry=?,region=?,scale=?,qualifications=?,needs=?,updated_at=? WHERE id='current'",[...fields.map(k=>String(x[k]??'').trim().slice(0,500)),new Date().toISOString()]).run();return Response.json(await statement(db,"SELECT * FROM company WHERE id='current'").first())}
 if(path==='/api/matches'){const c=await statement(db,"SELECT * FROM company WHERE id='current'").first();const terms=[c?.industry,c?.region,c?.scale,c?.qualifications,c?.needs].join(' ').split(/[,，、\s]+/).filter(x=>x.length>1).slice(0,20);if(!terms.length)return Response.json({company:c,items:[],message:'请先填写公司行业、地区或需求'});const clauses=terms.map(()=>'(instr(a.title,?)>0 OR instr(a.body,?)>0)');const params=terms.flatMap(x=>[x,x]);const items=await all(db,'SELECT a.id,a.title,a.url,a.summary,a.published_at,s.name source_name FROM articles a JOIN sources s ON s.id=a.source_id WHERE '+clauses.join(' OR ')+' ORDER BY a.published_at DESC LIMIT 100',params);return Response.json({company:c,items:items.map(a=>({...a,match_status:'可能符合',reason:'命中了企业档案中的关键词；仍需核对政策原文条件。'}))})}
 if(path==='/api/tasks'&&request.method==='GET'){const tasks=await all(db,"SELECT t.*,a.url article_url,a.published_at,s.name source_name FROM policy_tasks t LEFT JOIN articles a ON a.id=t.article_id LEFT JOIN sources s ON s.id=a.source_id WHERE t.deleted_at IS NULL ORDER BY COALESCE(t.deadline,t.plan_date) ASC");return Response.json({items:tasks})}
 if(path==='/api/tasks'&&request.method==='POST'){const x=await request.json();if(!x.article_id||!await statement(db,'SELECT id FROM articles WHERE id=?',[x.article_id]).first())throw new Error('政策不存在');const date=/^\d{4}-\d{2}-\d{2}$/.test(x.plan_date||'')?x.plan_date:null;const deadline=/^\d{4}-\d{2}-\d{2}$/.test(x.deadline||'')?x.deadline:null;const now=new Date().toISOString();const id=crypto.randomUUID();await statement(db,'INSERT INTO policy_tasks(id,company_id,article_id,title,plan_date,deadline,remind_days,status,note,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)',[id,'current',x.article_id,String(x.title||'').slice(0,300),date,deadline,Number(x.remind_days)||90,String(x.status||'待确认'),String(x.note||'').slice(0,2000),now,now]).run();return Response.json({id},{status:201})}
 if(path.startsWith('/api/tasks/')&&request.method==='PATCH'){const id=path.split('/').at(-1),x=await request.json();const allowed=['待确认','准备中','已提交','已完成','忽略','删除'];if(x.status&&!allowed.includes(x.status))throw new Error('无效的待办状态');const deleted=x.status==='删除'?new Date().toISOString():null;await statement(db,'UPDATE policy_tasks SET status=COALESCE(?,status),note=COALESCE(?,note),plan_date=COALESCE(?,plan_date),deadline=COALESCE(?,deadline),deleted_at=COALESCE(?,deleted_at),updated_at=? WHERE id=?',[x.status||null,x.note||null,x.plan_date||null,x.deadline||null,deleted,new Date().toISOString(),id]).run();return Response.json({saved:true})}
 if(path==='/api/articles'){
 const q=(u.searchParams.get('q')||'').trim().slice(0,200),source=u.searchParams.get('source'),category=u.searchParams.get('category'),params=[],clauses=[];
 for(const term of q.split(/\s+/).filter(Boolean).slice(0,8)){clauses.push('(instr(a.title,?)>0 OR instr(a.body,?)>0)');params.push(term,term)}
 if(source){clauses.push('a.source_id=?');params.push(source)}if(category){clauses.push('a.category=?');params.push(category)}
 if(u.searchParams.get('new')==='1'){clauses.push('a.collected_at>=?');params.push(chinaDayStart())}
 for(const [key,op] of [['from','>='],['to','<=']]){const value=u.searchParams.get(key);if(value&&/^\d{4}-\d{2}-\d{2}$/.test(value)){clauses.push('a.published_at'+op+'?');params.push(value)}}
 const where=clauses.length?' WHERE '+clauses.join(' AND '):'';const count=await statement(db,'SELECT count(*) total FROM articles a'+where,params).first();
 const page=Math.max(1,Math.min(10000,parseInt(u.searchParams.get('page'))||1));const rows=await all(db,'SELECT a.id,a.source_id,a.title,a.url,a.summary,a.published_at,a.collected_at,a.category,s.name source_name,'+(q?'substr(a.body,max(1,instr(a.body,?)-50),220)':'a.summary')+' excerpt FROM articles a JOIN sources s ON s.id=a.source_id'+where+' ORDER BY a.published_at DESC,a.collected_at DESC LIMIT 30 OFFSET ?',q?[q.split(/\s+/)[0],...params,(page-1)*30]:[...params,(page-1)*30]);return Response.json({items:rows,total:count.total,page,pages:Math.ceil(count.total/30),query:q});
 }
 if(path.startsWith('/api/articles/')){const row=await statement(db,'SELECT a.*,s.name source_name FROM articles a JOIN sources s ON s.id=a.source_id WHERE a.id=?',[path.split('/').at(-1)]).first();return Response.json(row||{error:'内容不存在'},{status:row?200:404})}
 if(path==='/api/sources'&&request.method==='POST'){
 const input=await request.json();const name=String(input.name||'').trim();if(!name||name.length>80)throw new Error('请填写 1–80 字的网站名称');const url=safeUrl(String(input.url||''));if(await statement(db,'SELECT id FROM sources WHERE url=?',[url]).first())throw new Error('该网址已经添加');const id=crypto.randomUUID();await statement(db,'INSERT INTO sources(id,name,url,created_at) VALUES (?,?,?,?)',[id,name,url,new Date().toISOString()]).run();return Response.json({id},{status:201})}
 if(path.startsWith('/api/sources/')&&request.method==='PATCH'){const id=path.split('/').at(-1),input=await request.json();if(typeof input.enabled!=='boolean')throw new Error('enabled 必须是布尔值');const r=await statement(db,'UPDATE sources SET enabled=? WHERE id=?',[Number(input.enabled),id]).run();return Response.json({changed:r.meta.changes})}
 if(path.startsWith('/api/sync/')&&request.method==='POST'){const id=path.split('/').at(-1);return Response.json(await syncSource(db,id,{limit:24}))}
 if(path==='/api/digests'&&request.method==='POST'){const input=await request.json();const body=String(input.body||'').trim();if(!body||body.length>30000)throw new Error('简报不能为空或超过 30000 字');if(!['Codex CLI','Codex 自动任务','规则整理'].includes(input.engine))throw new Error('无效的整理引擎');await statement(db,'INSERT INTO digests(id,created_at,body,engine) VALUES (?,?,?,?)',[crypto.randomUUID(),new Date().toISOString(),body,input.engine]).run();return Response.json({saved:true})}
 return Response.json({error:'接口不存在'},{status:404});
}
